"""clarifying_questions_with_reason

Revision ID: 5b563acce8e2
Revises: abb4cef61719
Create Date: 2026-05-06 19:21:09.327595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b563acce8e2'
down_revision: Union[str, Sequence[str], None] = 'abb4cef61719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clarifying_questions',
    sa.Column('question_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('element_id', sa.String(length=20), nullable=False),
    sa.Column('competency_name', sa.String(length=200), nullable=False),
    sa.Column('directed_at', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id'),
    sa.UniqueConstraint('match_id', 'element_id', 'directed_at', name='uq_question_match_element_direction')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clarifying_questions')
    # ### end Alembic commands ###
