"""add_coverage_to_matches

Revision ID: 84f19d97964b
Revises: e5e68c39dab4
Create Date: 2026-05-09 14:22:26.135805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84f19d97964b'
down_revision: Union[str, Sequence[str], None] = 'e5e68c39dab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('coverage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'coverage')
    # ### end Alembic commands ###
