"""tech_skills_table_and_recommendation_score

Revision ID: e5e68c39dab4
Revises: e2cef50eddeb
Create Date: 2026-05-09 11:57:20.971985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5e68c39dab4'
down_revision: Union[str, Sequence[str], None] = 'e2cef50eddeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tech_skills',
    sa.Column('tech_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('tech_id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('candidates', sa.Column('tech_keywords', sa.JSON(), nullable=True))
    op.add_column('job_post', sa.Column('tech_keywords', sa.JSON(), nullable=True))
    op.add_column('matches', sa.Column('recommendation_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'recommendation_score')
    op.drop_column('job_post', 'tech_keywords')
    op.drop_column('candidates', 'tech_keywords')
    op.drop_table('tech_skills')
    # ### end Alembic commands ###
